spring.datasource.url=jdbc:mysql://localhost:3306/dealvault
spring.datasource.username=root
spring.datasource.password=Sanket@0018

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp